# Generated by Django 3.2.9 on 2021-11-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_pics')),
                ('name', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=200)),
            ],
        ),
    ]
