# Generated by Django 3.2.9 on 2021-11-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicas', '0001_initial'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='demo',
        # ),
        migrations.AlterField(
            model_name='advisor_profile',
            name='image',
            field=models.ImageField(default='image/ava_doc.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='advisor_profile',
            name='info',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
