# Generated by Django 3.2.9 on 2021-11-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicas', '0004_alter_advisor_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor_profile',
            name='info',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
