# Generated by Django 3.2.9 on 2021-11-07 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medicas', '0005_alter_advisor_profile_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='DANH_SACH_SP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MASP', models.CharField(max_length=10)),
                ('TENSP', models.CharField(max_length=200)),
                ('PHANLOAI', models.CharField(max_length=100)),
                ('CONGDUNG', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MOTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MOTASP', models.CharField(max_length=1000)),
                ('VIEN', models.CharField(max_length=1000)),
                ('DOITUONG', models.CharField(max_length=1000)),
                ('LIEULUONG', models.CharField(max_length=1000)),
                ('BAOQUAN', models.CharField(max_length=1000)),
                ('THANTRONG', models.CharField(max_length=1000)),
                ('MASP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicas.danh_sach_sp')),
            ],
        ),
        migrations.CreateModel(
            name='INFOSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INFO', models.CharField(max_length=100)),
                ('THUONGHIEU', models.CharField(max_length=100)),
                ('SANXUAT', models.CharField(max_length=50)),
                ('MASP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicas.danh_sach_sp')),
            ],
        ),
    ]
