# Generated by Django 3.2.9 on 2021-11-10 00:49

import Medicas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicas', '0006_ad_specialty'),
    ]

#     operations = [
#         # migrations.CreateModel(
#         #     name='Specialty',
#         #     fields=[
#         #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#         #         ('specialty', models.CharField(max_length=50)),
#         #     ],
#         # ),
#         # migrations.AlterField(
#         #     model_name='ad_specialty',
#         #     name='specialty',
#         #     field=models.ForeignKey(on_delete=Medicas.models.Specialty, to='Medicas.advisor_profile'),
#         # ),
#     ]
