# Generated by Django 3.2.9 on 2021-11-10 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicas', '0007_auto_20211110_0749'),
    ]

#     operations = [
#         migrations.DeleteModel(
#             name='Ad_specialty',
#         ),
#     ]
