# Generated by Django 3.2.9 on 2021-11-10 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicas', '0008_delete_ad_specialty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialty',
            old_name='specialty',
            new_name='khoa',
        ),
    ]
