# Generated by Django 3.2.9 on 2021-11-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicas', '0006_danh_sach_sp_infosp_mota'),
        ('Medicas', '0009_rename_specialty_specialty_khoa'),
    ]

    operations = [
    ]
