# Generated by Django 3.2.9 on 2021-11-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicas', '0011_infosp_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infosp',
            name='URL',
        ),
        migrations.AddField(
            model_name='mota',
            name='URL',
            field=models.CharField(default='NULL', max_length=1000),
        ),
    ]
