# Generated by Django 3.2.9 on 2021-11-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicas', '0012_auto_20211126_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mota',
            name='URL',
            field=models.CharField(default='google.com', max_length=1000),
        ),
    ]
