# Generated by Django 3.2.9 on 2021-11-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicas', '0014_danh_sach_sp_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='danh_sach_sp',
            name='URL',
            field=models.CharField(default='google.com', max_length=1000),
        ),
    ]
