# Generated by Django 3.2.9 on 2021-11-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicas', '0015_danh_sach_sp_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor_profile',
            old_name='specialty',
            new_name='spec',
        ),
        migrations.AlterField(
            model_name='danh_sach_sp',
            name='INFO',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='danh_sach_sp',
            name='URL',
            field=models.CharField(max_length=1000),
        ),
    ]
