# Generated by Django 3.2.9 on 2021-11-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicas', '0016_auto_20211130_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialty',
            old_name='khoa',
            new_name='spec',
        ),
    ]
