# Generated by Django 3.2.9 on 2021-11-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicas', '0017_rename_khoa_specialty_spec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
