# Generated by Django 3.2.9 on 2021-11-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicas', '0018_delete_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(max_length=50)),
            ],
        ),
    ]
