# Generated by Django 3.2.9 on 2021-11-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicas', '0019_specialty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
