# Generated by Django 3.2.9 on 2021-12-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicas', '0023_doctor_profiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor_Profiles',
        ),
    ]
