# Generated by Django 3.2.9 on 2021-12-05 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Medicas', '0024_delete_doctor_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='ava_doc.jpg', null=True, upload_to='image/')),
                ('title', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=50)),
                ('info', models.CharField(blank=True, max_length=500)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
