# Generated by Django 3.2.9 on 2021-12-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicas', '0025_doctor_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profiles',
            name='image',
            field=models.ImageField(default='ava_doc.jpg', null=True, upload_to=''),
        ),
    ]
